--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PMMP-Plugin/KillToSteal
build-by-default: true
branches:
- main
projects:
  KillToSteal:
    path: ""
    libs:
      src: Muqsit/InvMenu/InvMenu
      version: ^4.1.0
...
